#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 800
#define PIXEL_WIDTH 5
#define PIXEL_HEIGHT 5

#define COLONNE 200  // = WINDOW_WIDTH / PIXEL_WIDTH
#define LIGNE 160  // = WINDOW_HEIGHT / PIXEL_HEIGHT

#define TARGET_R 0
#define TARGET_G 255
#define TARGET_B 0
